using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Path : MonoBehaviour
{
    public Transform Point;
    public Transform Point_1;
    public Transform Point_2;
    public Transform Point_3;
    public Transform Point_4;
    public Transform Point_5;
    public Transform Point_6;
    public Transform Point_7;
    public Transform Point_8;
    public Transform Point_9;
    public Transform Point_10;
    public Transform Point_11;
    public Transform Point_12;
    public Transform Point_13;
    public Transform Point_14;
    public Transform Point_15;
    public Transform Point_16;
    public Transform Point_17;
    public Transform Point_18;
    public Transform Point_19;
    public Transform Point_20;
    public Transform Point_21;
    public Transform Point_22;
    public Transform Point_23;
    public Transform Point_24;
    public Transform Point_25;
    public Transform Point_26;
    public Transform Point_27;
    public Transform Point_28;
    public Transform Point_29;
    public Transform Point_30;
    public Transform Point_31;
    public Transform Point_32;
    public Transform Point_33;
    public Transform Point_34;
    public Transform Point_35;
    public Transform Point_36;
    public Transform Point_37;
    public Transform Point_38;
    public Transform Point_39;
    public Transform Point_40;
    public Transform Point_41;
    public Transform Point_42;
    public Transform Point_43;
    public Transform Point_44;
    public Transform Point_45;
    public Transform Point_46;
    public Transform Point_47;
    public Transform Point_48;
    public Transform Point_49;
    public Transform Point_50;
    public Transform Point_51;
    public Transform Point_52;
    public Transform Point_53;
    public Transform Point_54;
    public Transform Point_55;
    public Transform Point_56;
    public Transform Point_57;
    public Transform Point_58;
    public Transform Point_59;
    public Transform Point_60;
    public Transform Point_61;
    public Transform Point_62;
    public Transform Point_63;
    public Transform Point_64;
}
